[workspace]
authors = ["matovitch <camille.brugel@laposte.net>"]
channels = ["conda-forge"]
name = "rh-memory"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
test = "python -m pytest"

[dependencies]
python = ">=3.14.4,<3.15"
pytorch = ">=2.10.0,<3"
ninja = "*"
cxx-compiler = "*"
pytest = "*"
